services:
  cstrike:
    build:
      context: .
      args:
        GAME_VARIANT: cstrike
    image: ghcr.io/libreturks/gameserver-hl:cstrike
    ports:
      - "27015:27015/udp"
      - "27015:27015/tcp"
    volumes:
      - ./cstrike:/opt/steam/custom
    command: -game cstrike +map de_dust2 +maxplayers 16
    restart: unless-stopped
