services:
  svencoop:
    ports:
      - 27015:27015
      - 27015:27015/udp
    image: mt190502/gameserver-hl:latest-svencoop
    # volumes:
      # - ./svencoop:/opt/steam/new-svencoop                 # For override
    command: -num_edicts 3072 +sv_lan 1 -console -port 27015 +log on +map 
